### ISSUE TITLE
Questions about the DCT space

### ISSUE THREAD

**Issue by SDOlivia** [yz-cnsdqz/MOJO-release#3]
Marvellous job!!
Since I new in this area, I wonder where do those DCT matrics (\eg dct_45.mat) in this come from and how to obtain a dct matrix with arbitrary dimension?

**Comment by SDOlivia** [comment]
I guess it's generated by matlab's function "dctmtx" to form the basis? Will some action prior be involved?

**Comment by SDOlivia** [comment]
BTW there is a small bug in eval_kps_pred.py, line 202 "traj_gt_arr = get_multimodal_gt()", no params are input.

**Comment by yz-cnsdqz** [comment]
Thanks for your interests :) That bug is fixed now.

In this work, I obtained these DCT (type II) basis from scipy. Matlab can do this job as well but was not tested. In principle, any lib should work here. Note that different libs might have different boundary conditions, which might produce different results.
